- mobile/lib/ChatScreen.dart
- mobile/lib/MainScreen.dart
- mobile/lib/SettingsScreen.dart
- mobile/lib/main.dart
- mobile/lib/model/SystemModel.dart
> Reworked models into single model

- mobile/lib/ChatScreen.dart
- mobile/lib/NewChatScreen.dart
- mobile/lib/model/SystemModel.dart
> Development frontend link new chat to user model

- backend/pom.xml
- backend/src/main/kotlin/za/ac/up/cs/atbash/service/MessageService.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/service/NotificationService.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/service/UserService.kt
> Development backend create structure

- backend/src/main/kotlin/za/ac/up/cs/atbash/domain/Message.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/domain/User.kt
> Added domain classes

- backend/src/main/kotlin/za/ac/up/cs/atbash/controller/MessageController.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/json/message/SendMessageRequestJson.kt
- backend/src/test/kotlin/za/ac/up/cs/atbash/controller/MessageControllerTest.kt
> Development backend validate send message body

- backend/src/main/kotlin/za/ac/up/cs/atbash/domain/User.kt
> Added table name specification to User entity

- backend/src/main/kotlin/za/ac/up/cs/atbash/service/MessageService.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/service/NotificationService.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/service/UserService.kt
> Development backend service stubs

- mobile/lib/domain/Message.dart
- mobile/lib/main.dart
- mobile/lib/service/MessageService.dart
- mobile/pubspec.lock
- mobile/pubspec.yaml
- mobile/test/domain/message_test.dart
- mobile/test/service/message_service_test.dart
> Added basic MessageService

- backend/pom.xml
- backend/src/main/kotlin/za/ac/up/cs/atbash/controller/UserController.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/domain/User.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/json/user/LoginRequestJson.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/json/user/LoginResponseJson.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/json/user/RegisterRequestJson.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/service/UserService.kt
- backend/src/test/kotlin/za/ac/up/cs/atbash/controller/UserControllerTest.kt
- backend/src/test/kotlin/za/ac/up/cs/atbash/service/MessageServiceTest.kt
- backend/src/test/kotlin/za/ac/up/cs/atbash/service/UserServiceTest.kt
> Completed Login Use Case

- backend/src/main/kotlin/za/ac/up/cs/atbash/controller/MessageController.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/domain/Message.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/json/message/SendMessageRequestJson.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/service/MessageService.kt
- backend/src/test/kotlin/za/ac/up/cs/atbash/controller/MessageControllerTest.kt
- backend/src/test/kotlin/za/ac/up/cs/atbash/service/MessageServiceTest.kt
> Changed sendMessage to accept User from

- backend/src/main/kotlin/za/ac/up/cs/atbash/controller/MessageController.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/domain/Message.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/json/message/SendMessageRequestJson.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/service/MessageService.kt
- backend/src/test/kotlin/za/ac/up/cs/atbash/controller/MessageControllerTest.kt
- backend/src/test/kotlin/za/ac/up/cs/atbash/service/MessageServiceTest.kt
> Added clientSideId to Message entity

- backend/pom.xml
- backend/src/main/kotlin/za/ac/up/cs/atbash/controller/UserController.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/domain/User.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/json/user/LoginResponseJson.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/service/UserService.kt
- backend/src/main/resources/application.properties
- backend/src/test/kotlin/za/ac/up/cs/atbash/service/MessageServiceTest.kt
- backend/src/test/kotlin/za/ac/up/cs/atbash/service/UserServiceTest.kt
> Replaced apiKey with jwtToken in login flow

- backend/src/main/kotlin/za/ac/up/cs/atbash/controller/UserController.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/domain/User.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/json/user/RegisterRequestJson.kt
- backend/src/main/kotlin/za/ac/up/cs/atbash/service/UserService.kt
- backend/src/test/kotlin/za/ac/up/cs/atbash/controller/UserControllerTest.kt
- backend/src/test/kotlin/za/ac/up/cs/atbash/service/MessageServiceTest.kt
- backend/src/test/kotlin/za/ac/up/cs/atbash/service/UserServiceTest.kt
> Added deviceToken to User entity

- backend/src/main/kotlin/za/ac/up/cs/atbash/service/MessageService.kt
- backend/src/test/kotlin/za/ac/up/cs/atbash/service/MessageServiceTest.kt
> Added deleteMessages function to messageService

- backend/src/test/kotlin/za/ac/up/cs/atbash/service/UserServiceIntegrationTest.kt
- backend/src/test/kotlin/za/ac/up/cs/atbash/service/UserServiceTest.kt
- backend/src/test/resources/application.properties
> Created and finished UserServiceIntegrationTest class

- backend/src/test/kotlin/za/ac/up/cs/atbash/controller/UserControllerIntegrationTest.kt
- backend/src/test/kotlin/za/ac/up/cs/atbash/controller/UserControllerTest.kt
> Created UserControllerIntegrationTest and coded all tests

- mobile/lib/main.dart
- mobile/lib/pages/LoginPage.dart
- mobile/test/loginPage_test.dart
> Added Unit/Widget tests for Login Page

- mobile/lib/pages/MainPage.dart
- mobile/lib/pages/SettingsPage.dart
- mobile/lib/services/UserService.dart
- mobile/test/mainPage_test.dart
- mobile/test/registrationPage_test.dart
> Wrote tests for mainPage_tests class

- mobile/lib/services/UserService.dart
- mobile/test/newChatPage_test.dart
> Finished tests for newChatPage_test class

- mobile/lib/pages/SettingsPage.dart
- mobile/lib/services/UserService.dart
- mobile/pubspec.lock
- mobile/pubspec.yaml
- mobile/test/loginPage_test.dart
- mobile/test/mainPage_test.dart
- mobile/test/mockingForPageTests.dart
- mobile/test/newChatPage_test.dart
- mobile/test/registrationPage_test.dart
- mobile/test/settingsPage_test.dart
> Wrote settings screen tests

- backend/src/main/kotlin/za/ac/up/cs/atbash/controller/UserController.kt
- backend/src/test/kotlin/za/ac/up/cs/atbash/controller/UserControllerTest.kt
> Created helo endpoint in UserController.kt

- backend/src/main/kotlin/za/ac/up/cs/atbash/controller/UserController.kt
- backend/src/test/kotlin/za/ac/up/cs/atbash/controller/UserControllerIntegrationTest.kt
- backend/src/test/kotlin/za/ac/up/cs/atbash/controller/UserControllerTest.kt
- mobile/lib/services/UserService.dart
> Changed login and register endpoints to use x-www-form-urlencoded

- backend/getusermessages/.gitignore
- backend/getusermessages/index.js
- backend/getusermessages/package-lock.json
- backend/getusermessages/package.json
- backend/template.yaml
> Added getusermessages microservice

- mobile/lib/pages/MainPage.dart
> Added image icon next to profile name in main page

- mobile/lib/domain/Contact.dart
- mobile/lib/services/ContactsService.dart
- mobile/lib/services/DatabaseService.dart
> Added status property to Contact entity

- mobile/lib/domain/Contact.dart
- mobile/lib/services/ContactsService.dart
- mobile/lib/services/DatabaseService.dart
> Added profileImage attribute to contact object

- mobile/lib/models/UserModel.dart
- mobile/lib/models/UserModel.g.dart
- mobile/lib/pages/SettingsPage.dart
- mobile/lib/services/UserService.dart
> Changed status to use mobx

- mobile/lib/pages/MainPage.dart
- mobile/lib/pages/NewChatPage.dart
- mobile/pubspec.lock
- mobile/pubspec.yaml
> Removed selectable chats and contacts, replaced with slideable button

- mobile/lib/pages/ProfileSettingsPage.dart
- mobile/lib/pages/SettingsPage.dart
> Added functionality to settings page

- mobile/lib/pages/RegistrationPage.dart
> Fixed register button not reappearing after failed register

- backend/get_number_prekeys/.gitignore
- backend/get_number_prekeys/__tests__/base64.js
- backend/get_number_prekeys/__tests__/index.test.js
- backend/get_number_prekeys/db_access.js
- backend/get_number_prekeys/index.js
- backend/get_number_prekeys/package-lock.json
- backend/get_number_prekeys/package.json
- backend/template.yaml
- backend/upload_keys/.gitignore
- backend/upload_keys/__tests__/base64.js
- backend/upload_keys/__tests__/index.test.js
- backend/upload_keys/db_access.js
- backend/upload_keys/index.js
- backend/upload_keys/package-lock.json
- backend/upload_keys/package.json
- mobile/lib/encryption/services/PreKeyStoreService.dart
- mobile/lib/main.dart
- mobile/lib/services/CommunicationService.dart
- mobile/lib/services/EncryptionService.dart
- mobile/lib/services/RegistrationService.dart
Added two backend methods to support this
> Added ability to top up prekeys

- backend/getusermessages/db_access.js
- backend/template.yaml
- mobile/lib/services/MessageboxService.dart
- mobile/lib/services/RegistrationService.dart
Fixed bugs with token creation and the downloading of offline messages
> Development messagebox bug fixes
